USE [SALE MANAGEMENT]
GO
SELECT * FROM [dbo].[CTHD] --- [SOHD, MASP]: Pri key
SELECT * FROM [dbo].[HOADON] --- [SOHD]: Pri key [MAKH, MANV]: Foreign Key
SELECT * FROM [dbo].[KHACHHANG] --- [MAKH]: Pri key
SELECT * FROM  [dbo].[NHANVIEN] --- [MANV]: Pri key
SELECT * FROM  [dbo].[SANPHAM] --- [MASP]: Pri key

--1. DOANH SỐ BÁN HÀNG CỦA TỪNG NHÂN VIÊN TRONG THÁNG 
SELECT FORMAT (A.NGHD,'yyyyMM') AS THANG, A. MANV, SUM(TRIGIA) AS 'DOANH SO'
    FROM HOADON A LEFT JOIN NHANVIEN B ON A.MANV = B.MANV
    GROUP BY FORMAT (A.NGHD,'yyyyMM'), A. MANV



--2. LẤY RA TÊN NHÂN VIÊN CÓ DOANH SỐ CAO NHẤT THEO NGÀY
CREATE PROCEDURE BEST_DAILY(@DATE VARCHAR(MAX))
AS 
BEGIN
    SELECT * FROM 
    (
        SELECT 
            FORMAT (NGHD,'yyyy-MM-dd') AS 'DATE'
            , A.MANV, HOTEN, SUM(TRIGIA) AS 'DOANH THU'
            , ROW_NUMBER () OVER ( PARTITION BY NGHD ORDER BY SUM(TRIGIA) DESC) AS RN
        FROM HOADON A LEFT JOIN NHANVIEN B ON A.MANV = B.MANV
        WHERE FORMAT (NGHD,'yyyy-MM-dd') = @DATE
        GROUP BY NGHD, A.MANV, HOTEN
    ) DAILY
    WHERE RN = 1
END

EXEC BEST_DAILY '2006-07-23'
    




--3.THỐNG KÊ DOANH SỐ BÁN HÀNG TRONG THÁNG THEO MAKH TẠI NGÀY CUỐI CÙNG CỦA THÁNG. TRONG ĐÓ PHAN LOAI KH NEW VÀ KH OLD TRONG NĂM 2006. 
--(BIẾT RẰNG NGAYDK <= NGAYHD, KH MỚI LÀ KH CÓ LỊCH SỬ MUA HÀNG LẦN ĐẦU TIÊN)
CREATE TABLE CUS_CATEGORY
(
     THANG INT
    ,MAKH VARCHAR (MAX)
    ,TOTALSALE FLOAT
    ,CLASSIFY VARCHAR (MAX)
)

ALTER PROCEDURE CATEGORY (@MAKH NVARCHAR (5), @THANG INT)
AS 
BEGIN

    DELETE FROM CUS_CATEGORY WHERE (MAKH = @MAKH AND THANG  = @THANG) -- XÓA DỮ LIỆU TRÙNG CỦA KHÁCH HÀNG

    INSERT INTO CUS_CATEGORY
        SELECT FORMAT(A.NGHD,'yyyMM'), A.MAKH, SUM(TRIGIA) AS TOTALSALE, 'OLD' AS 'CLASSIFY'
            FROM HOADON A LEFT JOIN KHACHHANG B ON A.MAKH = B.MAKH
            WHERE (A.NGHD > B.NGDK AND A.MAKH = @MAKH )
            GROUP BY FORMAT(A.NGHD,'yyyMM'), A.MAKH
   
    INSERT INTO CUS_CATEGORY
        SELECT FORMAT(A.NGHD,'yyyMM'), A.MAKH, SUM(TRIGIA) AS TOTALSALE, 'NEW' AS 'CLASSIFY'
            FROM HOADON A LEFT JOIN KHACHHANG B ON A.MAKH = B.MAKH
            WHERE (A.NGHD <= B.NGDK AND A.MAKH = @MAKH )
            GROUP BY FORMAT(A.NGHD,'yyyMM'), A.MAKH

END


EXEC CATEGORY 'KH01', '200608'
SELECT * FROM CUS_CATEGORY



--4.TÌM TOP 3 SẢN PHẨM BIẾN ĐỘNG SỐ LƯỢNG BÁN RA NHIỀU NHẤT/ ÍT NHẤT GIỮA CÁC NGÀY

ALTER PROCEDURE DELTA_SALE (@DATE1 DATE, @DATE2 DATE)
AS
BEGIN
    SELECT B.NGHD, MASP, SUM (SL) AS 'SL BAN RA'
    INTO #TEMP1
    FROM CTHD A LEFT JOIN HOADON B ON A.SOHD = B.SOHD
    WHERE NGHD = @DATE1
    GROUP BY B.NGHD, MASP
  
    SELECT B.NGHD, MASP, SUM (SL) AS 'SL BAN RA'
    INTO #TEMP2
    FROM CTHD A LEFT JOIN HOADON B ON A.SOHD = B.SOHD
    WHERE NGHD = @DATE2
    GROUP BY B.NGHD, MASP

    SELECT ISNULL(A.MASP, B.MASP) AS 'SAN PHAM', (ISNULL(A.[SL BAN RA],0) - ISNULL(B.[SL BAN RA], 0)) AS 'BIEN DONG'
    INTO #TEMP3
    FROM #TEMP1 A FULL JOIN #TEMP2 B ON A.MASP = B.MASP



    DECLARE @VAR1 NVARCHAR(MAX), @DELTA1 NVARCHAR(MAX)
    SELECT @VAR1 = [SAN PHAM], @DELTA1 = [BIEN DONG]
        FROM 
        (
            SELECT TOP 1 [SAN PHAM], [BIEN DONG] 
            FROM #TEMP3
            ORDER BY [BIEN DONG] DESC
        ) INCREASE
        PRINT N'' + @VAR1 + N' LA MA SAN PHAM TANG NHIEU NHAT: ' + @DELTA1 + N' SAN PHAM'

    DECLARE @VAR2 NVARCHAR(MAX), @DELTA2 NVARCHAR(MAX)
    SELECT @VAR2 = [SAN PHAM], @DELTA2 = [BIEN DONG]
        FROM 
        (
            SELECT TOP 1 [SAN PHAM], [BIEN DONG] 
            FROM #TEMP3
            ORDER BY [BIEN DONG] ASC
        ) DECREASE
        PRINT N'' + @VAR2 + N' LA MA SAN PHAM GIAM NHIEU NHAT: ' + @DELTA2 + N' SAN PHAM'

END


EXEC DELTA_SALE '2006-08-12', '2006-08-23'


--5. QUERY THÔNG TIN KHÁCH HÀNG, HIỂN THỊ MAKH, TUỔI, SINH NHẬT VÀO THỨ MẤY.
SELECT * FROM KHACHHANG

CREATE FUNCTION CUSTOM_INFO (@MAKH NVARCHAR(4))
RETURNS TABLE
AS RETURN
(
    SELECT MAKH, DATEPART(YEAR, NGDK) - DATEPART(YEAR, NGSINH) AS AGE,  DATEPART(WEEKDAY, NGDK) AS BIRTH_WEEKDAY  
    FROM KHACHHANG
    WHERE MAKH = @MAKH
)

SELECT * FROM CUSTOM_INFO ('KH01')


--6. TÌM THÔNG TIN KHÁCH HÀNG MUA NHIỀU SẢN PHẨM NHẤT VÀO NGÀY yyyy-mm-dd

SELECT * FROM HOADON

CREATE FUNCTION CUSTOM_MOSTBUY (@DAY DATE)
RETURNS TABLE
AS RETURN
(
    SELECT C.MAKH, SUM(SL) AS SOLUONG, RANK() OVER (ORDER BY SUM(SL) DESC) AS RN
    FROM CTHD A
        LEFT JOIN HOADON B ON A.SOHD = B.SOHD
        LEFT JOIN KHACHHANG C ON B.MAKH = C.MAKH
    WHERE @DAY = NGHD
    GROUP BY C.MAKH
)

SELECT * FROM CUSTOM_MOSTBUY ('2007-01-13')
WHERE RN = 1
